-- contact related tables
DROP TABLE PHONE;
DROP TABLE ADDRESS;
DROP TABLE CUSTOMER; 
DROP TABLE EMPLOYEE; 
DROP TABLE PERSON; 
 
-- Menu related tables
DROP TABLE ORDER_TAX_DETAIL;
DROP TABLE TAX;
DROP TABLE ORDER_DETAIL;
DROP TABLE ORDER_HEADER;
DROP TABLE ITEM_PROPERTY;
DROP TABLE ITEM;
DROP TABLE DISH;
DROP TABLE ATTRIBUTE_DISH_TYPE_ASSOCIATION;
DROP TABLE ATTRIBUTE_VALUE;
DROP TABLE ATTRIBUTE;
DROP TABLE DISH_TYPE;









